; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = WaveSentinel

[env:WaveSentinel]
platform = espressif32@6.4.0
board = um_pros3
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags = 
    -DLV_LVGL_H_INCLUDE_SIMPLE
	-D LV_CONF_INCLUDE_SIMPLE
	-I./include
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    -UARDUINO_USB_CDC_ON_BOOT
    -DDISABLE_ALL_LIBRARY_WARNINGS
    ; -DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
    
monitor_filters = esp32_exception_decoder

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
    crankyoldgit/IRremoteESP8266@^2.9.0
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git

lib_ignore = ESP32 BLE Arduino
