// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: WaveSentinel
//
// Original auto-generated layout removed — the Settings screen is now
// built at runtime in src/Display/SettingsScreen.h. We keep this stub
// so the linker is happy with the ui_scrSettings global and the
// `extern lv_obj_t * ui_*Settings*` declarations still referenced in
// other source files (they all resolve to NULL and the hand-coded
// SettingsScreen never touches them).
//
// Anything that used to live here (WiFi-mode switch, AP-OTA enable
// button, SSID/key entry, etc.) was obsolete after the move to HTTP
// OTA and would otherwise reappear after a rotation when ui_init()
// reruns.

#include "../ui.h"

void ui_scrSettings_screen_init(void)
{
    ui_scrSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSettings, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_scrSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
}
