// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "../ui.h"

void ui_scrRCSWMain_screen_init(void)
{
    ui_scrRCSWMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrRCSWMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrRCSWMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrRCSWMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrRCSWMain, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSWMain = lv_label_create(ui_scrRCSWMain);
    lv_obj_set_width(ui_lblRCSWMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWMain, 0);
    lv_obj_set_y(ui_lblRCSWMain, -223);
    lv_obj_set_align(ui_lblRCSWMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWMain, "RC SWITCH APPS");
    lv_obj_set_style_text_color(ui_lblRCSWMain, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWMain, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tabRCSWApps = lv_tabview_create(ui_scrRCSWMain, LV_DIR_BOTTOM, 30);
    lv_obj_set_width(ui_tabRCSWApps, 320);
    lv_obj_set_height(ui_tabRCSWApps, 364);
    lv_obj_set_x(ui_tabRCSWApps, 0);
    lv_obj_set_y(ui_tabRCSWApps, -18);
    lv_obj_set_align(ui_tabRCSWApps, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tabRCSWApps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tabRCSWApps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tabRCSWApps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_tabRCSWApps), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_tabRCSWApps), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_tabRCSWApps), &ui_font_Verdana18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_tabRCSWApps), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_tabRCSWApps), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_tabRCSWApps), lv_color_hex(0xFF9600),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_tabRCSWApps), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_tabRCSWApps), &ui_font_Verdana12,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TenPole = lv_tabview_add_tab(ui_tabRCSWApps, "Ten Pole");

    ui_btnTenPoleTxOn = lv_btn_create(ui_TenPole);
    lv_obj_set_width(ui_btnTenPoleTxOn, 80);
    lv_obj_set_height(ui_btnTenPoleTxOn, 60);
    lv_obj_set_x(ui_btnTenPoleTxOn, 14);
    lv_obj_set_y(ui_btnTenPoleTxOn, 108);
    lv_obj_set_align(ui_btnTenPoleTxOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTenPoleTxOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTenPoleTxOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTenPoleTxOn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTenPoleTxOn, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTenPoleTxOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnTenPoleTxOn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnTenPoleTxOn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTenPoleTxOn = lv_label_create(ui_btnTenPoleTxOn);
    lv_obj_set_width(ui_lblTenPoleTxOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTenPoleTxOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTenPoleTxOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTenPoleTxOn, "ON");
    lv_obj_set_style_text_align(ui_lblTenPoleTxOn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTenPoleTxOn, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTenPoleTxOff = lv_btn_create(ui_TenPole);
    lv_obj_set_width(ui_btnTenPoleTxOff, 80);
    lv_obj_set_height(ui_btnTenPoleTxOff, 60);
    lv_obj_set_x(ui_btnTenPoleTxOff, 101);
    lv_obj_set_y(ui_btnTenPoleTxOff, 108);
    lv_obj_set_align(ui_btnTenPoleTxOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTenPoleTxOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTenPoleTxOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTenPoleTxOff, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTenPoleTxOff, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTenPoleTxOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnTenPoleTxOff, lv_color_hex(0x3F882F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnTenPoleTxOff, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTenPoleTxOff = lv_label_create(ui_btnTenPoleTxOff);
    lv_obj_set_width(ui_lblTenPoleTxOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTenPoleTxOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTenPoleTxOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTenPoleTxOff, "OFF");
    lv_obj_set_style_text_align(ui_lblTenPoleTxOff, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTenPoleTxOff, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TenPoleSW0 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW0, 58);
    lv_obj_set_height(ui_TenPoleSW0, 20);
    lv_obj_set_x(ui_TenPoleSW0, -112);
    lv_obj_set_y(ui_TenPoleSW0, -140);
    lv_obj_set_align(ui_TenPoleSW0, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW0, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW0, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW0, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW0, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW1 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW1, 58);
    lv_obj_set_height(ui_TenPoleSW1, 20);
    lv_obj_set_x(ui_TenPoleSW1, -112);
    lv_obj_set_y(ui_TenPoleSW1, -110);
    lv_obj_set_align(ui_TenPoleSW1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW1, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW2 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW2, 58);
    lv_obj_set_height(ui_TenPoleSW2, 20);
    lv_obj_set_x(ui_TenPoleSW2, -112);
    lv_obj_set_y(ui_TenPoleSW2, -80);
    lv_obj_set_align(ui_TenPoleSW2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW2, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW3 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW3, 58);
    lv_obj_set_height(ui_TenPoleSW3, 20);
    lv_obj_set_x(ui_TenPoleSW3, -112);
    lv_obj_set_y(ui_TenPoleSW3, -50);
    lv_obj_set_align(ui_TenPoleSW3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW3, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW3, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW4 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW4, 58);
    lv_obj_set_height(ui_TenPoleSW4, 20);
    lv_obj_set_x(ui_TenPoleSW4, -112);
    lv_obj_set_y(ui_TenPoleSW4, -20);
    lv_obj_set_align(ui_TenPoleSW4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW4, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW4, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW5 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW5, 58);
    lv_obj_set_height(ui_TenPoleSW5, 20);
    lv_obj_set_x(ui_TenPoleSW5, -112);
    lv_obj_set_y(ui_TenPoleSW5, 10);
    lv_obj_set_align(ui_TenPoleSW5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW5, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW5, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW6 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW6, 58);
    lv_obj_set_height(ui_TenPoleSW6, 20);
    lv_obj_set_x(ui_TenPoleSW6, -111);
    lv_obj_set_y(ui_TenPoleSW6, 40);
    lv_obj_set_align(ui_TenPoleSW6, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW6, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW6, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW7 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW7, 58);
    lv_obj_set_height(ui_TenPoleSW7, 20);
    lv_obj_set_x(ui_TenPoleSW7, -112);
    lv_obj_set_y(ui_TenPoleSW7, 70);
    lv_obj_set_align(ui_TenPoleSW7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW7, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW7, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW8 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW8, 58);
    lv_obj_set_height(ui_TenPoleSW8, 20);
    lv_obj_set_x(ui_TenPoleSW8, -112);
    lv_obj_set_y(ui_TenPoleSW8, 100);
    lv_obj_set_align(ui_TenPoleSW8, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW8, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW8, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW8, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW8, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW9 = lv_switch_create(ui_TenPole);
    lv_obj_set_width(ui_TenPoleSW9, 58);
    lv_obj_set_height(ui_TenPoleSW9, 20);
    lv_obj_set_x(ui_TenPoleSW9, -112);
    lv_obj_set_y(ui_TenPoleSW9, 130);
    lv_obj_set_align(ui_TenPoleSW9, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW9, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW9, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW9, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblBit0 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit0, -48);
    lv_obj_set_y(ui_lblBit0, -141);
    lv_obj_set_align(ui_lblBit0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit0, "0");
    lv_obj_set_style_text_color(ui_lblBit0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit0, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit1 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit1, -48);
    lv_obj_set_y(ui_lblBit1, -110);
    lv_obj_set_align(ui_lblBit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit1, "0");
    lv_obj_set_style_text_color(ui_lblBit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit1, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit2 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit2, -48);
    lv_obj_set_y(ui_lblBit2, -81);
    lv_obj_set_align(ui_lblBit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit2, "0");
    lv_obj_set_style_text_color(ui_lblBit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit2, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit3 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit3, -48);
    lv_obj_set_y(ui_lblBit3, -50);
    lv_obj_set_align(ui_lblBit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit3, "0");
    lv_obj_set_style_text_color(ui_lblBit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit3, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit4 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit4, -48);
    lv_obj_set_y(ui_lblBit4, -21);
    lv_obj_set_align(ui_lblBit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit4, "0");
    lv_obj_set_style_text_color(ui_lblBit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit4, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit5 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit5, -48);
    lv_obj_set_y(ui_lblBit5, 10);
    lv_obj_set_align(ui_lblBit5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit5, "0");
    lv_obj_set_style_text_color(ui_lblBit5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit5, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit6 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit6, -48);
    lv_obj_set_y(ui_lblBit6, 39);
    lv_obj_set_align(ui_lblBit6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit6, "0");
    lv_obj_set_style_text_color(ui_lblBit6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit6, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit7 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit7, -48);
    lv_obj_set_y(ui_lblBit7, 69);
    lv_obj_set_align(ui_lblBit7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit7, "0");
    lv_obj_set_style_text_color(ui_lblBit7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit7, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit8 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit8, -48);
    lv_obj_set_y(ui_lblBit8, 99);
    lv_obj_set_align(ui_lblBit8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit8, "0");
    lv_obj_set_style_text_color(ui_lblBit8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit8, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit9 = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblBit9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit9, -48);
    lv_obj_set_y(ui_lblBit9, 130);
    lv_obj_set_align(ui_lblBit9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit9, "0");
    lv_obj_set_style_text_color(ui_lblBit9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit9, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddlTenProto = lv_dropdown_create(ui_TenPole);
    lv_dropdown_set_options(ui_ddlTenProto, "Type A (DIP)\nType B (Rotary)\nType C (Intertechno)\nType D (REV)");
    lv_obj_set_width(ui_ddlTenProto, 175);
    lv_obj_set_height(ui_ddlTenProto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlTenProto, 59);
    lv_obj_set_y(ui_ddlTenProto, -72);
    lv_obj_set_align(ui_ddlTenProto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlTenProto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_txt10PoleFreq = lv_textarea_create(ui_TenPole);
    lv_obj_set_width(ui_txt10PoleFreq, 173);
    lv_obj_set_height(ui_txt10PoleFreq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txt10PoleFreq, 59);
    lv_obj_set_y(ui_txt10PoleFreq, -123);
    lv_obj_set_align(ui_txt10PoleFreq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txt10PoleFreq, NULL);
    else lv_textarea_set_accepted_chars(ui_txt10PoleFreq, "1234567890.");
    lv_textarea_set_max_length(ui_txt10PoleFreq, 6);
    lv_textarea_set_text(ui_txt10PoleFreq, "433.92");
    lv_textarea_set_one_line(ui_txt10PoleFreq, true);
    lv_obj_set_style_text_color(ui_txt10PoleFreq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txt10PoleFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txt10PoleFreq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txt10PoleFreq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txt10PoleFreq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txt10PoleFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_lblRCSWStatus = lv_label_create(ui_TenPole);
    lv_obj_set_width(ui_lblRCSWStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWStatus, 61);
    lv_obj_set_y(ui_lblRCSWStatus, -38);
    lv_obj_set_align(ui_lblRCSWStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWStatus, "-");
    lv_obj_set_style_text_color(ui_lblRCSWStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblRCSWStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWStatus, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // =================================================================
    // Type B panel (Rotary: Address 1-4, Channel 1-4)
    // =================================================================
    ui_panelTypeB = lv_obj_create(ui_TenPole);
    lv_obj_set_width(ui_panelTypeB, 110);
    lv_obj_set_height(ui_panelTypeB, 280);
    lv_obj_set_x(ui_panelTypeB, -95);
    lv_obj_set_y(ui_panelTypeB, -5);
    lv_obj_set_align(ui_panelTypeB, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelTypeB, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_panelTypeB, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_opa(ui_panelTypeB, 0, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_panelTypeB, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(ui_panelTypeB, 0, LV_PART_MAIN);

    ui_lblTypeBAddr = lv_label_create(ui_panelTypeB);
    lv_obj_set_align(ui_lblTypeBAddr, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeBAddr, 0);
    lv_obj_set_y(ui_lblTypeBAddr, -80);
    lv_label_set_text(ui_lblTypeBAddr, "Address:");
    lv_obj_set_style_text_color(ui_lblTypeBAddr, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeBAddr, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeBAddr = lv_dropdown_create(ui_panelTypeB);
    lv_dropdown_set_options(ui_ddlTypeBAddr, "1\n2\n3\n4");
    lv_obj_set_width(ui_ddlTypeBAddr, 90);
    lv_obj_set_align(ui_ddlTypeBAddr, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeBAddr, 0);
    lv_obj_set_y(ui_ddlTypeBAddr, -45);

    ui_lblTypeBChan = lv_label_create(ui_panelTypeB);
    lv_obj_set_align(ui_lblTypeBChan, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeBChan, 0);
    lv_obj_set_y(ui_lblTypeBChan, 10);
    lv_label_set_text(ui_lblTypeBChan, "Channel:");
    lv_obj_set_style_text_color(ui_lblTypeBChan, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeBChan, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeBChan = lv_dropdown_create(ui_panelTypeB);
    lv_dropdown_set_options(ui_ddlTypeBChan, "1\n2\n3\n4");
    lv_obj_set_width(ui_ddlTypeBChan, 90);
    lv_obj_set_align(ui_ddlTypeBChan, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeBChan, 0);
    lv_obj_set_y(ui_ddlTypeBChan, 45);

    // =================================================================
    // Type C panel (Intertechno: Family a-f, Group 1-4, Device 1-4)
    // =================================================================
    ui_panelTypeC = lv_obj_create(ui_TenPole);
    lv_obj_set_width(ui_panelTypeC, 110);
    lv_obj_set_height(ui_panelTypeC, 280);
    lv_obj_set_x(ui_panelTypeC, -95);
    lv_obj_set_y(ui_panelTypeC, -5);
    lv_obj_set_align(ui_panelTypeC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelTypeC, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_panelTypeC, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_opa(ui_panelTypeC, 0, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_panelTypeC, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(ui_panelTypeC, 0, LV_PART_MAIN);

    ui_lblTypeCFamily = lv_label_create(ui_panelTypeC);
    lv_obj_set_align(ui_lblTypeCFamily, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeCFamily, 0);
    lv_obj_set_y(ui_lblTypeCFamily, -110);
    lv_label_set_text(ui_lblTypeCFamily, "Family:");
    lv_obj_set_style_text_color(ui_lblTypeCFamily, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeCFamily, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeCFamily = lv_dropdown_create(ui_panelTypeC);
    lv_dropdown_set_options(ui_ddlTypeCFamily, "a\nb\nc\nd\ne\nf");
    lv_obj_set_width(ui_ddlTypeCFamily, 90);
    lv_obj_set_align(ui_ddlTypeCFamily, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeCFamily, 0);
    lv_obj_set_y(ui_ddlTypeCFamily, -80);

    ui_lblTypeCGroup = lv_label_create(ui_panelTypeC);
    lv_obj_set_align(ui_lblTypeCGroup, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeCGroup, 0);
    lv_obj_set_y(ui_lblTypeCGroup, -35);
    lv_label_set_text(ui_lblTypeCGroup, "Group:");
    lv_obj_set_style_text_color(ui_lblTypeCGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeCGroup, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeCGroup = lv_dropdown_create(ui_panelTypeC);
    lv_dropdown_set_options(ui_ddlTypeCGroup, "1\n2\n3\n4");
    lv_obj_set_width(ui_ddlTypeCGroup, 90);
    lv_obj_set_align(ui_ddlTypeCGroup, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeCGroup, 0);
    lv_obj_set_y(ui_ddlTypeCGroup, -5);

    ui_lblTypeCDevice = lv_label_create(ui_panelTypeC);
    lv_obj_set_align(ui_lblTypeCDevice, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeCDevice, 0);
    lv_obj_set_y(ui_lblTypeCDevice, 40);
    lv_label_set_text(ui_lblTypeCDevice, "Device:");
    lv_obj_set_style_text_color(ui_lblTypeCDevice, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeCDevice, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeCDevice = lv_dropdown_create(ui_panelTypeC);
    lv_dropdown_set_options(ui_ddlTypeCDevice, "1\n2\n3\n4");
    lv_obj_set_width(ui_ddlTypeCDevice, 90);
    lv_obj_set_align(ui_ddlTypeCDevice, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeCDevice, 0);
    lv_obj_set_y(ui_ddlTypeCDevice, 70);

    // =================================================================
    // Type D panel (REV: Group A-D, Device 1-3)
    // =================================================================
    ui_panelTypeD = lv_obj_create(ui_TenPole);
    lv_obj_set_width(ui_panelTypeD, 110);
    lv_obj_set_height(ui_panelTypeD, 280);
    lv_obj_set_x(ui_panelTypeD, -95);
    lv_obj_set_y(ui_panelTypeD, -5);
    lv_obj_set_align(ui_panelTypeD, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelTypeD, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_panelTypeD, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_opa(ui_panelTypeD, 0, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_panelTypeD, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(ui_panelTypeD, 0, LV_PART_MAIN);

    ui_lblTypeDGroup = lv_label_create(ui_panelTypeD);
    lv_obj_set_align(ui_lblTypeDGroup, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeDGroup, 0);
    lv_obj_set_y(ui_lblTypeDGroup, -80);
    lv_label_set_text(ui_lblTypeDGroup, "Group:");
    lv_obj_set_style_text_color(ui_lblTypeDGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeDGroup, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeDGroup = lv_dropdown_create(ui_panelTypeD);
    lv_dropdown_set_options(ui_ddlTypeDGroup, "A\nB\nC\nD");
    lv_obj_set_width(ui_ddlTypeDGroup, 90);
    lv_obj_set_align(ui_ddlTypeDGroup, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeDGroup, 0);
    lv_obj_set_y(ui_ddlTypeDGroup, -45);

    ui_lblTypeDDevice = lv_label_create(ui_panelTypeD);
    lv_obj_set_align(ui_lblTypeDDevice, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblTypeDDevice, 0);
    lv_obj_set_y(ui_lblTypeDDevice, 10);
    lv_label_set_text(ui_lblTypeDDevice, "Device:");
    lv_obj_set_style_text_color(ui_lblTypeDDevice, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblTypeDDevice, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlTypeDDevice = lv_dropdown_create(ui_panelTypeD);
    lv_dropdown_set_options(ui_ddlTypeDDevice, "1\n2\n3");
    lv_obj_set_width(ui_ddlTypeDDevice, 90);
    lv_obj_set_align(ui_ddlTypeDDevice, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlTypeDDevice, 0);
    lv_obj_set_y(ui_ddlTypeDDevice, 45);

    // =================================================================
    // RAW TX tab
    // =================================================================
    ui_NEW = lv_tabview_add_tab(ui_tabRCSWApps, "RAW TX");

    // Status label
    ui_lblRawStatus = lv_label_create(ui_NEW);
    lv_obj_set_width(ui_lblRawStatus, 280);
    lv_obj_set_height(ui_lblRawStatus, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_lblRawStatus, 0);
    lv_obj_set_y(ui_lblRawStatus, -140);
    lv_obj_set_align(ui_lblRawStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRawStatus, "Enter code to transmit");
    lv_obj_set_style_text_color(ui_lblRawStatus, lv_color_hex(0xDEFF00), LV_PART_MAIN);
    lv_obj_set_style_text_align(ui_lblRawStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawStatus, &ui_font_Verdana14, LV_PART_MAIN);

    // Frequency label + textarea
    ui_lblRawFreq = lv_label_create(ui_NEW);
    lv_obj_set_align(ui_lblRawFreq, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblRawFreq, -120);
    lv_obj_set_y(ui_lblRawFreq, -108);
    lv_label_set_text(ui_lblRawFreq, "Freq:");
    lv_obj_set_style_text_color(ui_lblRawFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawFreq, &ui_font_Verdana14, LV_PART_MAIN);

    ui_txtRawFreq = lv_textarea_create(ui_NEW);
    lv_obj_set_width(ui_txtRawFreq, 140);
    lv_obj_set_height(ui_txtRawFreq, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_txtRawFreq, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_txtRawFreq, -15);
    lv_obj_set_y(ui_txtRawFreq, -108);
    lv_textarea_set_accepted_chars(ui_txtRawFreq, "1234567890.");
    lv_textarea_set_max_length(ui_txtRawFreq, 7);
    lv_textarea_set_text(ui_txtRawFreq, "433.92");
    lv_textarea_set_one_line(ui_txtRawFreq, true);
    lv_obj_set_style_text_color(ui_txtRawFreq, lv_color_hex(0x00FFEB), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_txtRawFreq, &ui_font_LCD20at8BPP, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_txtRawFreq, lv_color_hex(0x525052), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_txtRawFreq, 255, LV_PART_MAIN);

    // Code label + textarea
    ui_lblRawCode = lv_label_create(ui_NEW);
    lv_obj_set_align(ui_lblRawCode, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblRawCode, -120);
    lv_obj_set_y(ui_lblRawCode, -65);
    lv_label_set_text(ui_lblRawCode, "Code:");
    lv_obj_set_style_text_color(ui_lblRawCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawCode, &ui_font_Verdana14, LV_PART_MAIN);

    ui_txtRawCode = lv_textarea_create(ui_NEW);
    lv_obj_set_width(ui_txtRawCode, 140);
    lv_obj_set_height(ui_txtRawCode, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_txtRawCode, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_txtRawCode, -15);
    lv_obj_set_y(ui_txtRawCode, -65);
    lv_textarea_set_accepted_chars(ui_txtRawCode, "0123456789");
    lv_textarea_set_max_length(ui_txtRawCode, 10);
    lv_textarea_set_text(ui_txtRawCode, "0");
    lv_textarea_set_one_line(ui_txtRawCode, true);
    lv_obj_set_style_text_color(ui_txtRawCode, lv_color_hex(0x00FFEB), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_txtRawCode, &ui_font_LCD20at8BPP, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_txtRawCode, lv_color_hex(0x525052), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_txtRawCode, 255, LV_PART_MAIN);

    // Bit Length label + textarea
    ui_lblRawBitLen = lv_label_create(ui_NEW);
    lv_obj_set_align(ui_lblRawBitLen, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblRawBitLen, -120);
    lv_obj_set_y(ui_lblRawBitLen, -22);
    lv_label_set_text(ui_lblRawBitLen, "Bits:");
    lv_obj_set_style_text_color(ui_lblRawBitLen, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawBitLen, &ui_font_Verdana14, LV_PART_MAIN);

    ui_txtRawBitLen = lv_textarea_create(ui_NEW);
    lv_obj_set_width(ui_txtRawBitLen, 80);
    lv_obj_set_height(ui_txtRawBitLen, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_txtRawBitLen, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_txtRawBitLen, -45);
    lv_obj_set_y(ui_txtRawBitLen, -22);
    lv_textarea_set_accepted_chars(ui_txtRawBitLen, "0123456789");
    lv_textarea_set_max_length(ui_txtRawBitLen, 2);
    lv_textarea_set_text(ui_txtRawBitLen, "24");
    lv_textarea_set_one_line(ui_txtRawBitLen, true);
    lv_obj_set_style_text_color(ui_txtRawBitLen, lv_color_hex(0x00FFEB), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_txtRawBitLen, &ui_font_LCD20at8BPP, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_txtRawBitLen, lv_color_hex(0x525052), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_txtRawBitLen, 255, LV_PART_MAIN);

    // Pulse Length label + textarea
    ui_lblRawPulseLen = lv_label_create(ui_NEW);
    lv_obj_set_align(ui_lblRawPulseLen, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblRawPulseLen, -120);
    lv_obj_set_y(ui_lblRawPulseLen, 21);
    lv_label_set_text(ui_lblRawPulseLen, "Pulse:");
    lv_obj_set_style_text_color(ui_lblRawPulseLen, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawPulseLen, &ui_font_Verdana14, LV_PART_MAIN);

    ui_txtRawPulseLen = lv_textarea_create(ui_NEW);
    lv_obj_set_width(ui_txtRawPulseLen, 80);
    lv_obj_set_height(ui_txtRawPulseLen, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_txtRawPulseLen, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_txtRawPulseLen, -45);
    lv_obj_set_y(ui_txtRawPulseLen, 21);
    lv_textarea_set_accepted_chars(ui_txtRawPulseLen, "0123456789");
    lv_textarea_set_max_length(ui_txtRawPulseLen, 5);
    lv_textarea_set_text(ui_txtRawPulseLen, "350");
    lv_textarea_set_one_line(ui_txtRawPulseLen, true);
    lv_obj_set_style_text_color(ui_txtRawPulseLen, lv_color_hex(0x00FFEB), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_txtRawPulseLen, &ui_font_LCD20at8BPP, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_txtRawPulseLen, lv_color_hex(0x525052), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_txtRawPulseLen, 255, LV_PART_MAIN);

    // Protocol dropdown
    ui_lblRawProtocol = lv_label_create(ui_NEW);
    lv_obj_set_align(ui_lblRawProtocol, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblRawProtocol, -120);
    lv_obj_set_y(ui_lblRawProtocol, 64);
    lv_label_set_text(ui_lblRawProtocol, "Proto:");
    lv_obj_set_style_text_color(ui_lblRawProtocol, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawProtocol, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlRawProtocol = lv_dropdown_create(ui_NEW);
    lv_dropdown_set_options(ui_ddlRawProtocol, "1 (350us)\n2 (650us)\n3 (100us)\n4 (380us)\n5 (500us)\n6 (450us)");
    lv_obj_set_width(ui_ddlRawProtocol, 140);
    lv_obj_set_align(ui_ddlRawProtocol, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlRawProtocol, -15);
    lv_obj_set_y(ui_ddlRawProtocol, 64);

    // Repeat dropdown
    ui_lblRawRepeat = lv_label_create(ui_NEW);
    lv_obj_set_align(ui_lblRawRepeat, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_lblRawRepeat, -120);
    lv_obj_set_y(ui_lblRawRepeat, 107);
    lv_label_set_text(ui_lblRawRepeat, "Repeat:");
    lv_obj_set_style_text_color(ui_lblRawRepeat, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_lblRawRepeat, &ui_font_Verdana14, LV_PART_MAIN);

    ui_ddlRawRepeat = lv_dropdown_create(ui_NEW);
    lv_dropdown_set_options(ui_ddlRawRepeat, "1\n5\n10\n15\n20\n50");
    lv_dropdown_set_selected(ui_ddlRawRepeat, 2);
    lv_obj_set_width(ui_ddlRawRepeat, 80);
    lv_obj_set_align(ui_ddlRawRepeat, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_ddlRawRepeat, -45);
    lv_obj_set_y(ui_ddlRawRepeat, 107);

    // SEND button
    ui_btnRawTxSend = lv_btn_create(ui_NEW);
    lv_obj_set_width(ui_btnRawTxSend, 160);
    lv_obj_set_height(ui_btnRawTxSend, 45);
    lv_obj_set_x(ui_btnRawTxSend, 0);
    lv_obj_set_y(ui_btnRawTxSend, 155);
    lv_obj_set_align(ui_btnRawTxSend, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btnRawTxSend, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_btnRawTxSend, 8, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_btnRawTxSend, lv_color_hex(0x454545), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_btnRawTxSend, 255, LV_PART_MAIN);
    lv_obj_set_style_bg_grad_color(ui_btnRawTxSend, lv_color_hex(0xFF5500), LV_PART_MAIN);
    lv_obj_set_style_bg_grad_dir(ui_btnRawTxSend, LV_GRAD_DIR_VER, LV_PART_MAIN);

    ui_lblRawTxSend = lv_label_create(ui_btnRawTxSend);
    lv_obj_set_align(ui_lblRawTxSend, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRawTxSend, "SEND");
    lv_obj_set_style_text_font(ui_lblRawTxSend, &ui_font_Verdana18, LV_PART_MAIN);

    ui_btnRCSWBack = lv_btn_create(ui_scrRCSWMain);
    lv_obj_set_width(ui_btnRCSWBack, 90);
    lv_obj_set_height(ui_btnRCSWBack, 30);
    lv_obj_set_x(ui_btnRCSWBack, -114);
    lv_obj_set_y(ui_btnRCSWBack, 224);
    lv_obj_set_align(ui_btnRCSWBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRCSWBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnRCSWBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnRCSWBack, lv_color_hex(0x333355), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRCSWBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSWBack = lv_label_create(ui_btnRCSWBack);
    lv_obj_set_width(ui_lblRCSWBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblRCSWBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWBack, "BACK");
    lv_obj_set_style_text_color(ui_lblRCSWBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWBack, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelRCSWFreqKeyboard = lv_obj_create(ui_scrRCSWMain);
    lv_obj_set_width(ui_panelRCSWFreqKeyboard, 320);
    lv_obj_set_height(ui_panelRCSWFreqKeyboard, 480);
    lv_obj_set_align(ui_panelRCSWFreqKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_panelRCSWFreqKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_panelRCSWFreqKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelRCSWFreqKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelRCSWFreqKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_panelRCSWFreqKeyboard, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelRCSWFreqKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelRCSWFreqKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSWFreqKeyboardValueUnits = lv_label_create(ui_panelRCSWFreqKeyboard);
    lv_obj_set_width(ui_lblRCSWFreqKeyboardValueUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWFreqKeyboardValueUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWFreqKeyboardValueUnits, 0);
    lv_obj_set_y(ui_lblRCSWFreqKeyboardValueUnits, -165);
    lv_obj_set_align(ui_lblRCSWFreqKeyboardValueUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWFreqKeyboardValueUnits, "mHz");
    lv_obj_set_style_text_color(ui_lblRCSWFreqKeyboardValueUnits, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWFreqKeyboardValueUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWFreqKeyboardValueUnits, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSWFreqKeyboardTitle = lv_label_create(ui_panelRCSWFreqKeyboard);
    lv_obj_set_width(ui_lblRCSWFreqKeyboardTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWFreqKeyboardTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWFreqKeyboardTitle, 0);
    lv_obj_set_y(ui_lblRCSWFreqKeyboardTitle, -223);
    lv_obj_set_align(ui_lblRCSWFreqKeyboardTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWFreqKeyboardTitle, "Enter Value");
    lv_obj_set_style_text_color(ui_lblRCSWFreqKeyboardTitle, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWFreqKeyboardTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWFreqKeyboardTitle, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnTenPoleTxOn, ui_event_btnTenPoleTxOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTenPoleTxOff, ui_event_btnTenPoleTxOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW0, ui_event_TenPoleSW0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW1, ui_event_TenPoleSW1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW2, ui_event_TenPoleSW2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW3, ui_event_TenPoleSW3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW4, ui_event_TenPoleSW4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW5, ui_event_TenPoleSW5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW6, ui_event_TenPoleSW6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW7, ui_event_TenPoleSW7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW8, ui_event_TenPoleSW8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW9, ui_event_TenPoleSW9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txt10PoleFreq, ui_event_txt10PoleFreq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRCSWBack, ui_event_btnRCSWBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ddlTenProto, ui_event_ddlTenProto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRawTxSend, ui_event_btnRawTxSend, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtRawCode, ui_event_txtRawCode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtRawBitLen, ui_event_txtRawBitLen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtRawPulseLen, ui_event_txtRawPulseLen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtRawFreq, ui_event_txtRawFreq, LV_EVENT_ALL, NULL);

}
