// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: WaveSentinel

#include "../ui.h"

void ui_scrKybd_screen_init(void)
{
    ui_scrKybd = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrKybd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrKybd, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_scrKybd);
    lv_obj_set_width(ui_Keyboard1, 314);
    lv_obj_set_height(ui_Keyboard1, 240);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 52);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kybdCancel = lv_btn_create(ui_scrKybd);
    lv_obj_set_width(ui_kybdCancel, 100);
    lv_obj_set_height(ui_kybdCancel, 32);
    lv_obj_set_x(ui_kybdCancel, -97);
    lv_obj_set_y(ui_kybdCancel, 205);
    lv_obj_set_align(ui_kybdCancel, LV_ALIGN_CENTER);

    ui_lblKybdCancel = lv_label_create(ui_kybdCancel);
    lv_obj_set_width(ui_lblKybdCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblKybdCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdCancel, "Cancel");

    ui_txtKybdText = lv_textarea_create(ui_scrKybd);
    lv_obj_set_width(ui_txtKybdText, 288);
    lv_obj_set_height(ui_txtKybdText, 38);
    lv_obj_set_x(ui_txtKybdText, 0);
    lv_obj_set_y(ui_txtKybdText, -146);
    lv_obj_set_align(ui_txtKybdText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtKybdText, "Placeholder...");

    ui_lblKybdInformation = lv_label_create(ui_scrKybd);
    lv_obj_set_width(ui_lblKybdInformation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdInformation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdInformation, -1);
    lv_obj_set_y(ui_lblKybdInformation, -182);
    lv_obj_set_align(ui_lblKybdInformation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdInformation, "Enter Value");
    lv_obj_set_style_text_color(ui_lblKybdInformation, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblKybdInformation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_txtKybdText);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_kybdCancel, ui_event_kybdCancel, LV_EVENT_ALL, NULL);

}
