#!/usr/bin/env python3
"""
Convert a broken-glass PNG into an LVGL lv_img_dsc_t C source file.

Usage:
    python tools/convert_glass_png.py assets/broken_glass.png \
        --out src/Display/broken_glass_img.c --max 280

Behavior:
    - Downscales the source to fit within --max pixels on the longer side
      (default 280) so the firmware image stays under ~160 KB at RGB565+A
    - Outputs LV_IMG_CF_TRUE_COLOR_ALPHA (RGB565 + 1 byte alpha per pixel)
    - Pixels whose original luminance is below --black_thresh become fully
      transparent so the rat menu shows through the dark areas of the
      example screen-crack photo, leaving just the bright crack lines +
      glitch bands visible. Override with --no-keychroma to keep the
      whole frame opaque (use for a true "screen totally died" effect).
"""
import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("Pillow required: pip install Pillow\n")
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src", help="input PNG path")
    ap.add_argument("--out", required=True, help="output .c path")
    ap.add_argument("--max", type=int, default=280,
                    help="max side length after downscale (default 280)")
    ap.add_argument("--black_thresh", type=int, default=24,
                    help="luminance below this becomes transparent (0..255, default 24)")
    ap.add_argument("--no_keychroma", action="store_true",
                    help="disable black-key transparency; keep full opacity")
    ap.add_argument("--name", default="broken_glass_img",
                    help="C identifier for the lv_img_dsc_t (default broken_glass_img)")
    args = ap.parse_args()

    im = Image.open(args.src).convert("RGBA")
    w, h = im.size

    # Downscale so the longer side <= max
    scale = min(args.max / w, args.max / h, 1.0)
    if scale < 1.0:
        nw, nh = int(w * scale), int(h * scale)
        im = im.resize((nw, nh), Image.LANCZOS)
        w, h = im.size

    pixels = im.load()
    # 3 bytes per pixel: low byte RGB565, high byte RGB565, alpha
    out_bytes = bytearray(w * h * 3)
    p = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            # Black-key alpha
            if not args.no_keychroma:
                lum = (r * 30 + g * 59 + b * 11) // 100
                if lum < args.black_thresh:
                    a = 0
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out_bytes[p]     = rgb565 & 0xFF
            out_bytes[p + 1] = (rgb565 >> 8) & 0xFF
            out_bytes[p + 2] = a
            p += 3

    n = args.name
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/convert_glass_png.py — do not edit by hand.\n")
        f.write("#include <lvgl.h>\n\n")
        f.write("#ifdef __has_include\n")
        f.write("#  if __has_include(<lv_conf.h>)\n")
        f.write("#    include <lv_conf.h>\n")
        f.write("#  endif\n")
        f.write("#endif\n\n")
        f.write(f"const LV_ATTRIBUTE_LARGE_CONST uint8_t {n}_map[] = {{\n")
        for i in range(0, len(out_bytes), 16):
            chunk = out_bytes[i:i + 16]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write(f"const lv_img_dsc_t {n} = {{\n")
        f.write("    .header.cf       = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
        f.write("    .header.always_zero = 0,\n")
        f.write("    .header.reserved = 0,\n")
        f.write(f"    .header.w        = {w},\n")
        f.write(f"    .header.h        = {h},\n")
        f.write(f"    .data_size       = {len(out_bytes)},\n")
        f.write(f"    .data            = {n}_map,\n")
        f.write("};\n")
    bytes_kb = len(out_bytes) / 1024.0
    print(f"Wrote {args.out}  ({w}x{h}, {bytes_kb:.1f} KB image data)")


if __name__ == "__main__":
    main()
